// 车辆数据：差异化旋转 / 油箱 / 抓地 / 重量
// color 同时用于车架主色、骑手服条纹、关卡面板边框
export const VEHICLES = [
  {
    id: "trail",
    name: "山地车",
    icon: "🚲",
    desc: "均衡全能，新手之选",
    price: 0,
    drv: 1.0,
    spd: 1.0,
    grp: 1.0,
    wgt: 1.0,
    air: 1.0,
    tank: 1.0,
    color: "#314ccd",
  },
  {
    id: "sport",
    name: "竞速车",
    icon: "🏍️",
    desc: "极速快，空中旋转快，油箱小",
    price: 3000,
    drv: 1.35,
    spd: 1.4,
    grp: 0.72,
    wgt: 0.8,
    air: 1.4,
    tank: 0.75,
    color: "#e63946",
  },
  {
    id: "mud",
    name: "越野车",
    icon: "🚜",
    desc: "抓地强，耐撞，油箱大，旋转慢",
    price: 9000,
    drv: 1.12,
    spd: 0.7,
    grp: 1.45,
    wgt: 1.5,
    air: 0.75,
    tank: 1.45,
    color: "#8a5a2b",
  },
];
